# Generated by Django 4.0.4 on 2022-05-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carMake', models.CharField(default='', max_length=100)),
                ('carModel', models.CharField(blank=True, max_length=100)),
                ('carMileage', models.IntegerField(default=0)),
                ('carColor', models.CharField(default='', max_length=20)),
                ('carTransmission', models.CharField(default='', max_length=30)),
                ('carYear', models.IntegerField(default='')),
                ('carCylinders', models.CharField(blank=True, max_length=20)),
                ('carEngine', models.IntegerField(default='')),
                ('carFuel', models.CharField(default='', max_length=100)),
                ('carPrice', models.IntegerField(default=0)),
                ('link', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
