# Generated by Django 4.0.4 on 2022-05-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='carTransmission',
            field=models.CharField(choices=[('Manuel', 'Manuel'), ('AUTOMATIQUE', 'AUTOMATIQUE')], default='Manuel', max_length=30),
        ),
    ]
