# Generated by Django 4.0.2 on 2022-05-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0003_alter_car_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='carTransmission',
            field=models.CharField(default='', max_length=30),
        ),
    ]
