# Generated by Django 4.0.2 on 2022-05-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0004_alter_car_cartransmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='img',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
