# Generated by Django 4.0.2 on 2022-05-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0005_car_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
